name: Create Splunk application package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout latest tag
      uses: actions/checkout@v2

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Create SPL tarball archive
      uses: juankaram/archive-action@v1.0.0
      with:
        args: tar -czvf search_resource_utilization_app.spl search_resource_utilization_app

    - name: Upload SPL file for github release
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "*.spl"
        tags: false
        draft: false
        tag_name: ${{ steps.get_version.outputs.VERSION }}
